### ISSUE TITLE
Thank You (Ryan Ewen)

### ISSUE THREAD

**Issue by mohsinskynet** [RyanEwen/lan-cache-docker#20]
Working Nice and smooth as well then others like steamcache and other one ive tried so much lan caches but everyone have some problems .
I am a professional Mikrotik Certified i route all the traffic in reverse proxy for all the lan customers get that benefit i also really want to make cache epic games my backbone provider are caching epic games and other things we can help each other to make this possible if you have time.ty

**Comment by RyanEwen** [comment]
Hi @mohsinskynet 

Epic games use SSL so you would need to setup NGINX to accept SSL connections for that service - but that requires you creating an SSL certificate and then making it trusted, and installing it on each computer at the LAN. I have not done this so I am not sure I can help.
