### ISSUE TITLE
DNSMasq stuck restarting

### ISSUE THREAD

**Issue by asininedervish** [RyanEwen/lan-cache-docker#21]
Hi - the instructions seemed extremely straighforward, I ran through them on a clean Ubuntu 18.04 install, and both times I encountered the same error. When the containers start up, the dnsmasq one is stuck with a status of Restarting (2) 3 seconds ago  - the timer will slide up until it restarts the container again.

This is my first foray into Docker, so there is likely something I've done wrong, but I'm at a bit of a loss?

**Comment by RyanEwen** [comment]
What is the output of `docker-compose logs dnsmasq` ?

**Comment by asininedervish** [comment]
dnsmasq     | dnsmasq: failed to create listening socket for port 53: Address in use
dnsmasq     | Autodetected host IP as 192.168.10.162

**Comment by asininedervish** [comment]
It looks like something default on both Ubuntu server & desktop. VM's for both have the issue.

**Comment by asininedervish** [comment]
It was systemd - the following link resolved. Thanks!

https://unix.stackexchange.com/questions/304050/how-to-avoid-conflicts-between-dnsmasq-and-systemd-resolved
