### ISSUE TITLE
Possible Trojan Infection

### ISSUE THREAD

**Issue by HumanJHawkins** [RyanEwen/lan-cache-docker#22]
Unsure if this is overactive heuristics by Kaspersky or not, but I get reports of "HEUR:Trojan-Downloader.Shell.Agent.p" on cloning the lan-cache-docker repo. Although Kaspersky has been known to conflict with Docker, these symptoms are different than those reported in the known false-positive cases I've been able to find.

Log export from Kaspersky is attached:

[TrojanReport.txt](https://github.com/RyanEwen/lan-cache-docker/files/2152621/TrojanReport.txt)

**Comment by RyanEwen** [comment]
Hi,

It's definitely being overprotective. You can see the contents of the file it's blocking here: https://github.com/RyanEwen/lan-cache-docker/blob/master/docker-nginx/Dockerfile

The file a Dockerfile, which tells Docker step-by-step instructions on how to download NGINX (web server program) source code and compile it with custom settings needed for the lan-cache.

**Comment by HumanJHawkins** [comment]
Ah... I should have thought to look at that. Thanks.
