### ISSUE TITLE
Question: ipv6

### ISSUE THREAD

**Issue by tango-kilo** [RyanEwen/lan-cache-docker#6]
Does this work with ipv6? Or does it require ipv6 be disabled in the router or on each PC on the LAN?
Thanks in advance.

**Comment by RyanEwen** [comment]
It only works with ipv4 but you shouldn't have to disable ipv6 on any PCs. You should probably disable it on your router, if you've setup your router to use ipv6 with your ISP (I don't think any router or ISP has this setup by-default)

**Comment by tango-kilo** [comment]
Thanks for the rapid reply. ipv6 is enabled by default for Comcast xfinity and now in many Cox cable areas, so is becoming more common.

**Comment by RyanEwen** [comment]
That's nice to see IPv6 finally getting pushed. I don't think it would be too hard to support it here but I don't know the IPv6 addresses for each of the services and my ISP is not currently rolling out IPv6 for me to test :(
