### ISSUE TITLE
Question: disable or remove a service

### ISSUE THREAD

**Issue by tango-kilo** [RyanEwen/lan-cache-docker#7]
If I wanted to remove a service, for example xbox live, which requires a spoofed SSL cert, do I just delete the xbox dnsmasq and nginx conf files and do the following?
 docker-compose down
 docker-compose up -d

The reason for asking, the lan cache was preventing login to Microsoft Store based games, Sea of Thieves beta specifically. One I had the attendees manually set real DNS and flush they were able to login.

**Comment by RyanEwen** [comment]
Yes, that should do what you want.

SSL traffic should get proxied through unchanged without breaking it, I'll report back if I did the issue you're seeing.
